# Generated by Django 3.2.25 on 2025-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20250917_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitstopapplication',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='pitstopapplication',
            name='preferred_shifts',
        ),
        migrations.AddField(
            model_name='pitstopapplication',
            name='weekly_schedule',
            field=models.JSONField(default=dict, help_text='Weekly schedule: {"Mon": ["7-4", "8-5"], "Tue": ["9-5"], ...} - each day can have multiple time slots'),
        ),
    ]
