# Generated by Django 3.2.25 on 2026-01-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_fix_blob_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload client resume', null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload document file', upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='WorkerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Phone number for login (must match client phone)', max_length=20, unique=True)),
                ('pin_hash', models.CharField(help_text='Hashed 4-6 digit PIN for authentication', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this worker can access the portal')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether account is approved by staff')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time after too many failed attempts', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='Staff member who created account', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('client', models.OneToOneField(help_text='Link to client record', on_delete=django.db.models.deletion.CASCADE, related_name='worker_account', to='clients.client')),
            ],
            options={
                'verbose_name': 'Worker Account',
                'verbose_name_plural': 'Worker Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('bathroom', 'Bathroom Issue'), ('supplies', 'Supplies Needed'), ('safety', 'Safety Concern'), ('equipment', 'Equipment Problem'), ('cleaning', 'Cleaning Issue'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text='Brief description of issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the problem')),
                ('location_detail', models.CharField(blank=True, help_text='Specific location at site (e.g., "North bathroom", "Storage closet")', max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the issue', null=True, upload_to='service_requests/')),
                ('acknowledged_by', models.CharField(blank=True, help_text='Staff member who acknowledged', max_length=100)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Person assigned to fix', max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(help_text='Worker who submitted this request', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='clients.client')),
                ('work_site', models.ForeignKey(help_text='Site where issue is located', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='clients.worksite')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'priority'], name='clients_ser_status_4e522a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['work_site', 'status'], name='clients_ser_work_si_a4079e_idx'),
        ),
    ]
