# Generated by Django 3.2.25 on 2026-01-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_add_worker_portal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerSessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('worker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clients.workeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workersessiontoken',
            index=models.Index(fields=['token'], name='clients_wor_token_e178b7_idx'),
        ),
        migrations.AddIndex(
            model_name='workersessiontoken',
            index=models.Index(fields=['expires_at'], name='clients_wor_expires_d58046_idx'),
        ),
    ]
