# Generated by Django 3.2.25 on 2026-01-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20260115_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='typical_end_time',
            field=models.TimeField(blank=True, help_text='Typical shift end time (optional)', null=True),
        ),
    ]
