# Generated by Django 3.2.25 on 2026-05-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_worker_shift_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertimepunch',
            name='work_site',
            field=models.ForeignKey(blank=True, help_text='PitStop location selected for this clock in/out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_punches', to='clients.worksite'),
        ),
        migrations.AddField(
            model_name='worksite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for clock-in/out geofence validation.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='worksite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for clock-in/out geofence validation.', max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='workertimepunch',
            index=models.Index(fields=['work_site', 'clock_out_at'], name='clients_wor_work_si_478f76_idx'),
        ),
    ]
