# Generated by Django 3.2.25 on 2026-05-23 20:56
"""
Drop the iceboxed worker-portal models that are no longer in the iPad clock workflow:

- OpenShift / ShiftCoverInterest — never wired into the active worker portal.
- WorkerShiftProof — replaced by WorkerTimePunch (clock in/out).
- WorkerPortalNote — feature iceboxed; admin already unregistered.
- WorkerTimeOffRequest — feature iceboxed; admin already unregistered.
- ServiceRequest — feature iceboxed; admin already unregistered.

Order matters because of foreign-key chains:
    1. Drop unique constraint on ShiftCoverInterest (references open_shift).
    2. Drop ShiftCoverInterest (FK -> OpenShift, WorkerAccount).
    3. Drop OpenShift.
    4. Drop WorkerShiftProof (FK -> WorkAssignment, WorkerAccount).
    5. Drop WorkerPortalNote.
    6. Drop WorkerTimeOffRequest.
    7. Drop ServiceRequest (FK -> Client, WorkSite).
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_auto_20260522_2113'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shiftcoverinterest',
            name='uniq_worker_openshift_interest',
        ),
        migrations.DeleteModel(
            name='ShiftCoverInterest',
        ),
        migrations.DeleteModel(
            name='OpenShift',
        ),
        migrations.DeleteModel(
            name='WorkerShiftProof',
        ),
        migrations.DeleteModel(
            name='WorkerPortalNote',
        ),
        migrations.DeleteModel(
            name='WorkerTimeOffRequest',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
