# Generated by Django 3.2.25 on 2026-05-28 22:54
"""
Add a single unpaid meal break (lunch) to WorkerTimePunch.

All fields are nullable, so existing punches stay valid (null lunch =
net hours equal gross hours). Paid 10-minute rest breaks are intentionally
not tracked because they don't change net paid hours.

The auto-generated migration also picked up unrelated pre-existing index-name
and choice-label drift from earlier migrations; that noise is omitted here so
this migration only does what its name says.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_prune_iceboxed_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertimepunch',
            name='lunch_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workertimepunch',
            name='lunch_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workertimepunch',
            name='lunch_start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workertimepunch',
            name='lunch_start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workertimepunch',
            name='lunch_end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workertimepunch',
            name='lunch_end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
