# Generated by Django 5.1.15 on 2026-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_documentuploadinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clienttextmessage',
            new_name='clients_cli_client__8136b7_idx',
            old_name='clients_cli_client__94003a_idx',
        ),
        migrations.RenameIndex(
            model_name='clienttextmessage',
            new_name='clients_cli_status_d4b421_idx',
            old_name='clients_cli_status_c15e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='clienttextmessage',
            new_name='clients_cli_directi_163495_idx',
            old_name='clients_cli_directi_58870c_idx',
        ),
        migrations.RenameIndex(
            model_name='workertimepunch',
            new_name='clients_wor_worker__aff04e_idx',
            old_name='clients_wor_worker__0a4f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='workertimepunch',
            new_name='clients_wor_assignm_cb0f7b_idx',
            old_name='clients_wor_assignm_53725a_idx',
        ),
        migrations.RenameIndex(
            model_name='workertimepunch',
            new_name='clients_wor_clock_i_c84d81_idx',
            old_name='clients_wor_clock_i_1f10d7_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='citybuild_files_confirmed',
            field=models.BooleanField(default=False, help_text='Staff confirmed City Build file packet reviewed (optional).'),
        ),
        migrations.AlterField(
            model_name='client',
            name='demographic_info',
            field=models.CharField(choices=[('american_indian', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('black', 'Black or African American'), ('white', 'Caucasian or White'), ('hispanic_latinx', 'Hispanic or Latin X'), ('middle_eastern', 'Middle Eastern'), ('pacific_islander', 'Native Hawaiian or Other Pacific Islander'), ('other', 'Other'), ('decline_state', 'Decline to State'), ('multiracial', 'Multiracial')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('sf_residency', 'Proof of SF Residency'), ('hs_diploma', 'High School Diploma / GED'), ('id', 'Government ID'), ('photo_release', 'Photo Release Form'), ('employment_proof', 'Proof of Employment'), ('self_attestation', 'Employment Self-Attestation'), ('intake', 'Intake Form'), ('consent', 'Consent Form'), ('certificate', 'Certificate/Credential'), ('reference', 'Reference Letter'), ('cb_application', 'CityBuild Application'), ('cb_roi', 'Release of Information'), ('cb_tabe', 'TABE'), ('cb_parq', 'Par-Q / Doc Clearance'), ('cb_iep', 'IEP'), ('cb_ssn_card', 'Social Security Card'), ('cb_drug_test', 'Drug Test'), ('cb_safety', 'Safety Form'), ('cb_covid_vax', 'COVID Vaccination'), ('cb_po', 'PO'), ('cb_besi', 'BESI'), ('cb_jrt_eval', 'JRT Eval'), ('cb_rights', 'Rights & Responsibilities'), ('cb_lou', 'Letter of Understanding & Agreement'), ('cb_interview', 'Interview Sheet'), ('cb_emp_edu_verify', 'Employment & Education Verification'), ('cb_support_svc', 'Supportive Service Determination'), ('other', 'Other Document')], default='other', max_length=20),
        ),
    ]
