# Generated by Django 3.2.25 on 2025-09-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20250815_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PitStopApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_work_us', models.BooleanField(default=False)),
                ('is_veteran', models.BooleanField(default=False)),
                ('position_applied_for', models.CharField(max_length=100)),
                ('available_start_date', models.DateField(blank=True, null=True)),
                ('employment_desired', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('relief_list', 'Relief List')], max_length=20)),
                ('available_days', models.JSONField(default=list, help_text='List of days available e.g. ["Mon","Tue"]')),
                ('preferred_shifts', models.JSONField(default=list, help_text='List of shift codes from SHIFT_CHOICES')),
                ('employment_history', models.JSONField(default=list, help_text='List of up to 2 jobs with fields: company, city, state, manager, phone, title, responsibilities, start_date, end_date')),
                ('education_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitstop_applications', to='clients.client')),
            ],
            options={
                'verbose_name': 'Pit Stop Application',
                'verbose_name_plural': 'Pit Stop Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
