# Generated by Django 3.2.25 on 2025-09-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20250917_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitstopapplication',
            name='employment_history',
            field=models.JSONField(default=list, help_text='Last job with fields: company, city, state, manager, phone, title, responsibilities, start_date, end_date'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title or description', max_length=255)),
                ('doc_type', models.CharField(choices=[('resume', 'Resume'), ('intake', 'Intake Form'), ('consent', 'Consent Form'), ('id', 'Identification'), ('certificate', 'Certificate/Credential'), ('reference', 'Reference Letter'), ('other', 'Other Document')], default='other', max_length=20)),
                ('file', models.FileField(help_text='Upload document file', upload_to='client-docs/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.CharField(help_text='Staff member who uploaded this document', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
