# Generated by Django 3.2.25 on 2025-09-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20250917_2219'),
        ('clients', '0004_auto_20250917_2220'),
    ]

    operations = [
    ]
