# Generated by Django 3.2.25 on 2025-09-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_merge_0004_auto_20250917_2219_0004_auto_20250917_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='job_company',
            field=models.CharField(blank=True, help_text='Company where client was placed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='job_hourly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly wage for placed job', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='job_placed',
            field=models.BooleanField(default=False, help_text='Was client placed in a job after program completion?'),
        ),
        migrations.AddField(
            model_name='client',
            name='job_placement_date',
            field=models.DateField(blank=True, help_text='Date when client was placed in job', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title/position client was placed in', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='program_completed_date',
            field=models.DateField(blank=True, help_text='Date when client completed their program', null=True),
        ),
    ]
